name = "merchant-receipt-statistics"
pages_build_output_dir = "client/dist"
compatibility_date = "2026-06-08"

[[d1_databases]]
binding = "DB"
database_name = "merchant-receipt-statistics"
database_id = "6c1556c0-4945-44a0-a451-0cd873806725"
